CREATE TABLE `tbl_test_module` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) ,
  `mobile_no` VARCHAR(15) UNIQUE,
  `email` VARCHAR(50) UNIQUE,
  `status` ENUM('0','1') DEFAULT '1',
  `is_deleted` ENUM('0','2') DEFAULT '0',
  `created_on` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_on` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
